### ISSUE TITLE
BCL Conversion Failing.

### ISSUE THREAD

**Issue by ChabbyTMD** [sanjaynagi/AmpSeeker#69]
Workflow throws a 
`ChildIOException:
File/directory is a child to another output:` when provided with an Illumina data folder.

**Comment by sanjaynagi** [comment]
I dont get any such error on my machine trevor - Could you provide some more info? 

is your branch up to date?

**Comment by sanjaynagi** [comment]
We really need to add a BCL folder to the testing suite, though. 

At the minute the CI is only testing from reads, its not thorough enough.

**Comment by sanjaynagi** [comment]
It could also be a snakemake version issue. What version are you on? 

It seems to be OK with 7.25.0

**Comment by ChabbyTMD** [comment]
Hi Sanjay,

Yes my branch is up-to-date. I was testing the workflow again with the latest additions on the dataset that Martin generated here at UVRI. After setting everything up and running the workflow that's when I got that error. 

I agree, the workflow must be tested for both read and BCL conversion modes to ensure it's robust enough. As for the BCL folder for the test suite, won't we run into folder size constraints? Because I'm not sure how we can avoid a multi-gigabyte folder upload for the test case. I'm open to suggestions on this.

You make a great point though, it might be a Snakemake version issue on my end. I'm currently running version 6.12.3.

**Comment by sanjaynagi** [comment]
Can you try updating snakemake and see? Would be useful to know. Calvin did a nano kit run which is 458Mb. We may be able to host it somewhere and download it within the CI. Sent from my iPhoneOn 11 Jul 2023, at 17:47, Trevor Mugoya ***@***.***> wrote:﻿
Hi Sanjay,
Yes my branch is up-to-date. I was testing the workflow again with the latest additions on the dataset that Martin generated here at UVRI. After setting everything up and running the workflow that's when I got that error.
I agree, the workflow must be tested for both read and BCL conversion modes to ensure it's robust enough. As for the BCL folder for the test suite, won't we run into folder size constraints? Because I'm not sure how we can avoid a multi-gigabyte folder upload for the test case. I'm open to suggestions on this.
You make a great point though, it might be a Snakemake version issue on my end. I'm currently running version 6.12.3.
